site_name: ZeroNet
site_url: https://github.com/HelloZeroNet/ZeroNet
site_description: Decentralized websites using Bitcoin crypto and the BitTorrent network

repo_url: https://github.com/HelloZeroNet/ZeroNet

extra_css: [docs.css]
extra_javascript: [docs.js]


pages:
- [index.md, Introduction]

- [index.md, Using ZeroNet, Introduction]
- [using_zeronet/installing.md, Using ZeroNet, Installing]
- [using_zeronet/sample_sites.md, Using ZeroNet, Sample sites]
- [using_zeronet/create_new_site.md, Using ZeroNet, Create new site]

- [site_development/getting_started.md, Site Development, Getting Started]
- [site_development/zeroframe_api_reference.md, Site Development, ZeroFrame API reference]
- [site_development/content_json.md, Site Development, Structure of content.json]
- [site_development/dbschema_json.md, Site Development, Structure of dbschema.json]

- [zeronet_development/coding_conventions.md, ZeroNet Development, Coding conventions]
- [zeronet_development/network_protocol.md, ZeroNet Development, Network protocol]
- [zeronet_development/contributing.md, ZeroNet Development, Contributing to ZeroNet]
- [zeronet_development/donate.md, ZeroNet Development, Donation]

theme: readthedocs
