site_name: ZeroNet
site_url: https://github.com/HelloZeroNet/ZeroNet
site_description: Decentralized websites using Bitcoin crypto and the BitTorrent network

repo_url: https://github.com/HelloZeroNet/ZeroNet

extra_css: [docs.css]

pages:
- [index.md, Index]
- [developing.md, Developing, How to start]
- [zeroframe_api.md, Developing, ZeroFrame API reference]

theme: readthedocs