site_name: ZeroNet
site_url: https://github.com/HelloZeroNet/ZeroNet
site_description: Decentralized websites using Bitcoin crypto and the BitTorrent network

repo_url: https://github.com/HelloZeroNet/ZeroNet

extra_css: [docs.css]
extra_javascript: [docs.js]

pages:
- [index.md, Index]

- [getting_started/installing.md, Getting Started, Installing]
- [getting_started/create_new_site.md, Getting Started, Create new site]

- [site_development/debug_mode.md, Site Development, Start ZeroNet in Debug mode]
- [site_development/using_zeroframe_api.md, Site Development, Using ZeroFrame API]
- [site_development/zeroframe_api_reference.md, Site Development, ZeroFrame API reference]

theme: readthedocs