site_name: ZeroNet
site_url: https://github.com/HelloZeroNet/ZeroNet
site_description: Decentralized websites using Bitcoin crypto and the BitTorrent network

repo_url: https://github.com/HelloZeroNet/ZeroNet

extra_css: [docs.css]
extra_javascript: [docs.js]


pages:
- [index.md, Introduction]

- [getting_started/installing.md, Getting Started, Installing]
- [getting_started/create_new_site.md, Getting Started, Create new site]
- [getting_started/sample_sites.md, Getting Started, Sample sites]

- [site_development/debug_mode.md, Site Development, Start ZeroNet in Debug mode]
- [site_development/using_zeroframe_api.md, Site Development, ZeroFrame API Example]
- [site_development/zeroframe_api_reference.md, Site Development, ZeroFrame API reference]
- [site_development/content_json.md, Site Development, Structure of content.json]
- [site_development/dbschema_json.md, Site Development, Structure of dbschema.json]

- [zeronet_development/coding_conventions.md, ZeroNet Development, Coding conventions]
- [zeronet_development/network_protocol.md, ZeroNet Development, Network protocol]
- [zeronet_development/contributing.md, ZeroNet Development, Contributing to ZeroNet]
- [zeronet_development/donate.md, ZeroNet Development, Donation]

theme: readthedocs
